### ISSUE TITLE
Creating a Source from multiple Sources

### ISSUE THREAD

**Issue by EnriqueSampaio** [VoidXH/Cavern#114]
Hello again, I have another question about how to use Cavern's API, and if what I want is possible using only Cavern.

Basically, at the moment I have several sources with one channel each (clip with one channel), what I want is to combine these sources into a single source with all these channels (multichannel waveform clip), or, combine these sources into a source with a mono channel that is a combination of these channels.

My ultimate goal with this is to have a source playing a clip composed by multiple audio channels (or a mono channel generated from multiple channels) in the same bed.

Any help or suggestions on how to approach this would be appreciated, thanks in advance!

**Comment by VoidXH** [comment]
If you want to play multiple files as one channel, the quick way is to add them at the same location as different sources. The better option is to load all of them with the `Read` function of the `AudioReader`, which gets all samples from a file, then mix them together with `WaveformUtils.Mix`. Then, create a new `Clip` from the result and attach it to a `Source`. To prevent clipping, because the resulting level is unknown, you can use `WaveformUtils.Normalize` or `MultichannelWaveform.Normalize`, depending on what construction you're using.

**Comment by EnriqueSampaio** [comment]
Thank you sir!
I think something is missing in the sources I create, I've tried adding them to static channels, I've tried to give them a position and attach them to the listener, but I can never hear them in the final result. The ADM gets the size, sample rate, bit depth and duration I want, but no sound at all. When I use my AudioReader's renderer sources this doesn't happen, I manage to manipulate and listen to them without problems. Can you help me identify what's missing?

Here's an example of how I'm creating the sources:
```
AudioReader myReader = AudioReader.Open("<path to .wav 48000/16>");

float[] myData = myReader.Read();
float[] monoMix = new float[myData.Length];

WaveformUtils.Mix(myData, monoMix);

Clip myClip = new(monoMix, 1, 48000);
Source mySource = new Source()
{
    Clip = myClip
};
```

I've also tried to give it a position on creation (ex: Position = Vector3(10, 0 0)) but the result is the same. Also tried to copy settings (Source.copySettings) from a "valid" source (sources generated by the AudioReader's renderer, that I can listen on final ADM), but no success.

**Comment by VoidXH** [comment]
Try it with the latest commit.

**Comment by EnriqueSampaio** [comment]
Worked like a charm! Thanks!
