### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ElliottDyson** [VoidXH/Cavern#122]
First of all, absolutely love what you're doing here!

However, I do have an idea for ASIO/ASIO4ALL implementation, this way the program wouldn't be constrained to the typical 8-channel limit of most operating systems and we could theoretically expand to as many channels a sound card might support.

What do you think?

Also, if you are accepting support for this project, I would love to help contribute. :)

**Comment by VoidXH** [comment]
Because Cavern always builds on existing audio frameworks, a Cavern-supplied ASIO output wouldn't be used. For example, you can have massively multichannel output from Cavern-generated WAV files and some ASIO players. There is currently no channel limit on Cavernize's side for export, you can already do anything up to 65535 channels. The other version that will be made of Cavern (a decoder/filter) won't have such limitation either.
