### ISSUE TITLE
Encode ADM to E-AC3 JOC

### ISSUE THREAD

**Issue by EnriqueSampaio** [VoidXH/Cavern#133]
Hello, firstly good work guys, amazing tool!

I was wondering if using the Cavern API, or putting together pieces of it, I would be able to somehow encode an ADM BWF to E-AC3 JOC (Dolby Digital Plus with Dolby Atmos), with the intention of muxing this in a container (MP4 probably).

Could you help me by giving me some guidance on how can I approach to do this? If this is not possible with the current implementations on Cavern, do you know of any document that could help me implement this?

Thank in advance!

**Comment by VoidXH** [comment]
Use the Enhanced AC-3 Merger tool after you rendered the ADM to a multichannel WAV. That will be a valid Atmos file. JOC encoding is not possible, so the file won't be small enough to pass through optical, but it will work with HDMI and will give the same result. Better, actually.

**Comment by EnriqueSampaio** [comment]
@VoidXH thanks for the answer. Enhanced AC-3 Merger constructor expects Enhanced AC-3 streams (e.g. streams from EnhancedAC3Reader), but right now I have only one stream, from my atmos WAV file (opened with RIFFWaveReader), so if I pass that stream to the merger constructor, errors occur when trying to read the EAC3 header, as expected. There's some steps that I'm skipping in the middle so my atmos WAV file can be used with the Enhanced AC-3 Merger tool? (I'm using the Cavern.Format.Transcoders.EnhancedAC3Merger class).

Thanks!

**Comment by VoidXH** [comment]
By Enhanced AC-3 Merger, I meant the tool under CavernSamples, not the class. E-AC-3 encoding has to be done by FFmpeg, since BAP/coefficient encoding is not yet implemented for E-AC-3 transcoding. The entire process is the following, and does not require coding:
- Import the content into Cavernize and export it in your desired channel layout.
- Import the rendered file into Enhanced AC-3 Merger, and export to E-AC-3.

The result will be a channel-based render of the content. Because the bitrate will be way over DD+ Atmos content, the resulting quality is actually better than using JOC. Objects will not be preserved, but this doesn't have any effect on spatial accuracy. Refer to the [render guidelines](https://github.com/VoidXH/Cavern/blob/master/docs/Guidelines%20for%20object-based%20movie%20audio.md) for proof.
