### ISSUE TITLE
Weird artifacts when playing DD+ Atmos 

### ISSUE THREAD

**Issue by electrolyte-orb** [VoidXH/Cavern#146]
https://github.com/VoidXH/Cavern/assets/55880176/fd303e3d-18f1-4bd6-9fdc-930c8e0494d5

**Comment by electrolyte-orb** [comment]
maybe its due to partial support for EAC3 + JOC?? Not sure

**Comment by VoidXH** [comment]
This is just the headphone virtualizer's distortion. To get a quality headphone experience, render the content and use something like HeSuVi.

**Comment by ThreeDeeJay** [comment]
> This is just the headphone virtualizer's distortion. To get a quality headphone experience, render the content and use something like HeSuVi.

@VoidXH I still get these artifacts in the Unity player even when setting the speaker layout to 7.1 Surround (with or without HeSuVi) so perhaps this may be related to [sparse DD+ JOC decoding](https://github.com/VoidXH/Cavern/issues/17#issuecomment-1268149518)?
- [MP4](https://web.archive.org/web/20230225220642/http://media.developer.dolby.com/Atmos/MP4/Universe_Fury2.mp4): same artifacts as shown above.
- [LAF](https://mega.nz/file/DexURLjY#weYtezaZ9CFiX0AVkBPQWrZ4sc0PHLr5oY2rhAmAch0) (converted from MP4 above): loud static noise instead of the audio getting distorted
- [ADM](https://www.blackmagicdesign.com/dvres/dr17-dolby-atmos-project): Plays mostly fine, just some crackling
- [LAF](https://mega.nz/file/7fRnGCBI#eaJCMs8emSzxbrrMmR8HL_ZGKIIgsRUP6L1LFRlmlpc) (converted from ADM) same as above.

On a side note, the OpenAL Soft developer implemented a [LAF decoder](https://github.com/kcat/openal-soft/commit/3b10c6f9bc83e535f5de119f668ce6fd17e4e67d).
I put together [OpenALSoftLAFPlayer.zip](https://github.com/user-attachments/files/16537038/OpenALSoftLAFPlayer.zip) which is pre-configured for HRTF playback (more settings by [editing alsoft.ini](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample)) and can replace the HRTF MHR with any of [these](https://kutt.it/FindOpenALSoftHRTF), convert a SOFA with [makemhr](https://github.com/kcat/openal-soft/releases) or just delete it to use the built-in MIT KEMAR HRTF instead of my preferred one (SADIE II H6). Note that sparse JOC LAF issues are still present with this decoder, though at least crackling seems gone, so perhaps you might wanna consider implementing OpenAL Soft for rendering and [other features](https://github.com/kcat/openal-soft/blob/51c6bc5bfcf535708c3473f1539e4d14c971e4a7/README.md?plain=1#L7) 👀👌

**Comment by VoidXH** [comment]
Sparse JOC is currently muted, but I'll reopen this to take a look.

**Comment by VoidXH** [comment]
I have tested all files and they all work with the latest stable release. The minor playback issues are indeed caused by sparse JOC.
