### ISSUE TITLE
Under Virtual Presets, there's no 7.1.6?

### ISSUE THREAD

**Issue by Sawtaytoes** [VoidXH/Cavern#167]
Under the Virtual Presets, I'm not seeing a 7.1.6:
![image](https://github.com/VoidXH/Cavern/assets/3948069/1d1a75d7-0117-45ab-ae76-f60939117591)
Not sure if it even matters to add it, but wouldn't that affect how bed-layers speakers are setup? Or is it that there are always only 2 bedlayer tops? Which tops are in the bed layer? The middle two (referred to as top side)?

I can't seem to find any of these presets with height speakers. They have tops, but not heights. I'm wondering if heights make a difference. I wanna know what sounds come out of them versus what comes out of the tops, but I'd need to be able to set my tops as heights. Would changing the H/X value fix that?

**Comment by VoidXH** [comment]
These were chosen as the top 5 most common 8+ channel layouts. You could just remove wides from 9.1.6, channel locations don't change between layouts.

Tops and heights are practically the same, AVRs just call them one way or the other, but play the same exact sounds. In Cavern, if you're putting the speakers lower, it would mean more and faster transitions to them, since the limit of object movements is the ceiling (unlike half of it for Dolby's reference implementation).

**Comment by Sawtaytoes** [comment]
> if you're putting the speakers lower, it would mean more and faster transitions to them, since the limit of object movements is the ceiling (unlike half of it for Dolby's reference implementation).

Faster transitions to height speakers because they're farther down? I thought the height speakers were supposed to be (in Atmos) at the top-most portion of the wall in the front and back of the room. Is it just Cavern that handles them differently if set as heights instead of tops?

Also, what do you mean by half of the ceiling is the limit of objects in the Dolby reference implementation?

**Comment by VoidXH** [comment]
> I thought the height speakers were supposed to be (in Atmos) at the top-most portion of the wall in the front and back of the room.

Heights are Auro and somewhat ProLogic. Atmos has a ground layer (middle of the wall in cinemas) and a top layer.

> Is it just Cavern that handles them differently if set as heights instead of tops?

As far as I know, only Cavern and Trinnov handle speaker placement correctly, others just work with the discrete outputs of a 9.1.6 render.


> Also, what do you mean by half of the ceiling is the limit of objects in the Dolby reference implementation?

[See this.](https://github.com/VoidXH/Cavern/blob/master/docs/Guidelines%20for%20object-based%20movie%20audio.md#known-differences)

**Comment by Sawtaytoes** [comment]
> Heights are Auro and somewhat ProLogic. Atmos has a ground layer (middle of the wall in cinemas) and a top layer.

My receiver supports this Dolby Atmos 7.1.6 layout with front and rear heights rather than tops:
![image](https://github.com/VoidXH/Cavern/assets/3948069/971423c1-6a8c-4641-b33a-5a28328b1915)
Source: https://www.dolby.com/about/support/guide/speaker-setup-guides/7.1.6-mounted-overhead-speakers-setup-guide/

This is how I've setup my room. I would expect this to sound different because the heights are gonna track more closely to the cube shape in the Dolby Atmos Renderer than the sphere shape you'd get by making them tops.

> [See this.](https://github.com/VoidXH/Cavern/blob/master/docs/Guidelines%20for%20object-based%20movie%20audio.md#known-differences) If they reach half the height, they'll be completely on the top layer.

There's a guy who provided an Atmos download, and when I play that back on my system, the only time objects are out of the ground speakers is when it's 100% on the top. If not, it images between them.

That's why I'm wondering about this 50%. It might be true, but it's not how my receiver is processing those objects.

**Comment by VoidXH** [comment]
> This is how I've setup my room. I would expect this to sound different because the heights are gonna track more closely to the cube shape in the Dolby Atmos Renderer than the sphere shape you'd get by making them tops.

Most Atmos renderers work with room boundaries, regardless of what you set up. You front left will always render objects which are at the front left corner of your room. Because sound designers always expect a wall-to-wall screen (they don't mix for homes), this manifested in the home as "put your fronts next to your screen".

These soundstage warpings are a compromise and are normal. These official speaker positions exaggerate the mapped space in different ways, but the sound they render to top channels are always made for the corner or the side edge of the room. This is visible when you load up a channel-based Atmos demo, like Overwatch, which is a 9.1.6 pre-render.
