### ISSUE TITLE
Poor audio quality

### ISSUE THREAD

**Issue by Slimbizkit** [VoidXH/Cavern#193]
After decoding to PCM format, I get audio files with a frequency cutoff at 17 kHz. Below I present example spectrograms of decoding e-ac3 joc file with cavernize (adm bwf compact) and ffmpeg.

I have Windows 10 22H2
ffmpeg version ffmpeg version n5.1.6-9-gdcdfd7fb62-20241103
CavernizeGUI v2.0.2.

Cavernize
![Audio Object 2_Cavernize](https://github.com/user-attachments/assets/c0a03f83-7230-44f5-a832-d425becd7f6f)

FFMPEG
![ffmpeg C](https://github.com/user-attachments/assets/52074739-c23b-403a-bb8c-028ee92f40c7)

**Comment by VoidXH** [comment]
This is SPX (Spectral Extension), a feature [not implemented](https://cavern.sbence.hu/cavern/doc.php?p=Cavernize&tab=cd) in Cavern's AC-3 decoder. SPX rolls up low frequency signal as upper harmonics, and blends them with noise, this is the same as Crystality. Because this is not actual audio information, implementation is not on the critical path.

One workaround when rendering Atmos with Cavern is using the FFmpeg-decoded PCM file with the --override-bed command.
