### ISSUE TITLE
Feature Request : Import Dolby PHRTF to Headphone Virtualizer.

### ISSUE THREAD

**Issue by bluewidy** [VoidXH/Cavern#50]
https://games.dolby.com/phrtf/games-instructions/

Dolby currently provides an app to generate PHRTF files via smartphones. This file is applicable to the binaural renderer of the Dolby Atmos Production Suite or the binaural renderer of Dolby Atmos for Headphones and start a personalized binaural rendering process.

If can apply PHRTF files to Cavern Driver or Cavernize's headphone virtualizer, it will be a more powerful program!

P.S. I can provide you with my Dolby PHRTF file if you'd like to check it out. Or you can generate a PHRTF file through the link I posted.

**Comment by VoidXH** [comment]
Please attach a sample, I'll se if it's doable or encrypted.

**Comment by bluewidy** [comment]
[bluewindy's PHRTF.zip](https://github.com/VoidXH/Cavern/files/10143094/bluewindy.s.PHRTF.zip)

Thank you for your interest.

**Comment by VoidXH** [comment]
Sadly this is a JSON file with initial coefficients for a simulation that will later be done in Dolby software, so the raw HRIR coefficients can't be read from the file.

**Comment by bluewidy** [comment]
Sir, It's the IRs for 7.1.4 using this channel order! I was able to make it with the help of 3DJ.
![channel order](https://user-images.githubusercontent.com/40682277/205435118-2c7ed87d-b4c3-4d66-811f-8312cc74d0f2.png)

**Comment by VoidXH** [comment]
The second one could work, but is this a standard process? Can it be exported from Dolby software in this format? I want to support custom HRTFs, but do it in a standard way, not in a new format, and this sounds like a deconvolution with the original Dolby noise test.

**Comment by ThreeDeeJay** [comment]
Hi @VoidXH, you're right: this isn't really a standard format but rather an admittedly hacky way to capture Dolby's personalized HRTF which seems to use a new, non-standard and possibly even proprietary/encrypted format for HRTF, when they could've just used the actual standard: SOFA, which I hope Cavern supports in the future 😉 
Speaking of, you might wanna check out the [SOFA spatializer for Unity](https://github.com/sofacoustics/SOFAlizer-for-Unity), which I recently [compiled here](https://github.com/ThreeDeeJay/SOFAlizer-for-Unity/releases/tag/latest). It might make it easier to implement SOFA support in Cavern, though I haven't tested it yet and it hasn't been updated in a while.

Anyhow, I just suggested this method because @bluewidy really wanted to use their pHRTF in Cavern and since it seems to use [regular stereo IRs for convolution of virtualize speakers](https://github.com/VoidXH/HRTF/blob/master/Equalizer%20APO%20examples/45_0_ultraflat.wav), I figured it might be worth trying the same [principle used to capture any virtual surround into HRIRs](https://sourceforge.net/p/hesuvi/wiki/How-To%20Record%20Impulse%20Responses%20Digitally/) to use in [HeSuVi](https://sourceforge.net/projects/hesuvi/), but also including height channels.
That's why I made [Dirac_delta_7.1.4.zip](https://github.com/VoidXH/Cavern/files/10146836/Dirac_delta_7.1.4.zip) (highest channel count supported in [WWSpatialAudioPlayer](https://sourceforge.net/p/playpcmwin/wiki/WWSpatialAudioPlayer/), a MS Spatial Sound API audio player that uses the [12-channel layout above](https://user-images.githubusercontent.com/40682277/205442058-c3dfcc1d-362d-40d9-b24e-495d98ede623.png)) and [Dirac_delta_9.1.6.zip](https://github.com/VoidXH/Cavern/files/10146837/Dirac_delta_9.1.6.zip) for Movies & TV.
Then I had @bluewidy record the WASAPI loopback while those files are being played, so we just wanted to know if that format was usable before committing to editing 16+ IRs.
Even if Cavern gets SOFA support, something like this would probably be the only way to import an HRTF without a SOFA file available. But hey, not like there's a shortage of [SOFA options](https://airtable.com/shruimhjdSakUPg2m) 😄

**Comment by VoidXH** [comment]
I'll add support for raw IR files like this one first.

**Comment by bluewidy** [comment]
> The second one could work

[bluewindy's 9.1.6 IRs.zip](https://github.com/VoidXH/Cavern/files/10147102/bluewindy.s.9.1.6.IRs.zip)
Sir, I brought the 9.1.6 IRs from Pop Sound that you said work.

**Comment by VoidXH** [comment]
Done in f0e3d657ef2a8049102955fc0f9ebfb4c506db64, released.
