### ISSUE TITLE
why volume is different between 714 and 512？

### ISSUE THREAD

**Issue by kaedewang** [VoidXH/Cavern#98]
512：
![图片](https://user-images.githubusercontent.com/67850015/227396909-8b00e1c4-dc13-48ce-a499-348b3db1b231.png)

714：
![图片](https://user-images.githubusercontent.com/67850015/227396860-411506fc-01ad-49e2-9d7b-6c15e6a23b25.png)

**Comment by VoidXH** [comment]
If you only have 2 heights, volume will be reduced by -3 dB to prevent clipping. Some content (like Overwatch) has the top fronts and sides maxed out, and this is what fixes it. For 4 heights, this is not needed, the resulting track can be louder, which is desirable as Atmos tracks don't always have equal gains with the downmix.

**Comment by kaedewang** [comment]
So about #88 the lastest clipping issue of render 5.1.2front, does it also need to reduce -3 dB volume?
It seems that volume of 5.1.2front is louder than 5.1.2side.
5.1.2front
![图片](https://user-images.githubusercontent.com/67850015/227472007-444da3a7-f6f6-45dd-9505-76210e30abf3.png)

5.1.2side
![图片](https://user-images.githubusercontent.com/67850015/227472054-f7c78b92-8dfe-4cc3-9bcc-91886e12e8ea.png)

**Comment by kaedewang** [comment]
> If you only have 2 heights, volume will be reduced by -3 dB to prevent clipping. Some content (like Overwatch) has the top fronts and sides maxed out, and this is what fixes it. For 4 heights, this is not needed, the resulting track can be louder, which is desirable as Atmos tracks don't always have equal gains with the downmix.

I can understand why to reduce -3 dB volume for surround and height speaker. Maybe two speakers' tracks mix to one.
But I don't know why ch1-ch4 are also reduced, they are same in either 512 or 714.

**Comment by VoidXH** [comment]
5.1.2 front is not rendered as 5.1.2, it's 5.1.4, but the surrounds and surround heights are mixed together. This is because the renderer by definition can't handle triangles. This rendering method is also used for Dolby Atmos itself. Volume is not decreased in this case, because the heights are not handling the entire plane, just their front counterparts. For 5.1.2 side, volume decrease is required, because it can and will happen that the entire sound output comes from them.

**Comment by kaedewang** [comment]
> the surrounds and surround heights are mixed together
> Volume is not decreased in this case
So the surrounds of 5.1.2 front may be clipping???
And I can't find that Dolby supports 5.1.2 front but only 5.1.2 side.

**Comment by kaedewang** [comment]
I checked Dolby 2016 demo 0034(512 layout) and 0035(514 layout).
The render result is different by DRP and Cavern.

512 by DRP doesn't reduce -3 dB volume.
Left DRP; Right Cavern
![图片](https://user-images.githubusercontent.com/67850015/227826830-fd0e8938-645f-4981-a45d-0a6d8f255134.png)

LFE by Cavern is lower than DRP.
Left DRP; Right Cavern
![图片](https://user-images.githubusercontent.com/67850015/227826569-ae85519c-9484-453d-9f66-5ea3f8c1b4bd.png)

**Comment by kaedewang** [comment]
I also checked 0037(714 layout).
I remember this issue was fixed before. Is it right?
LFE by Cavern is lower than DRP.
Left DRP; Right Cavern
![图片](https://user-images.githubusercontent.com/67850015/227831556-590b1f0d-7846-4e93-bd13-8f1e548a107d.png)

**Comment by kaedewang** [comment]
So when tuning LFE, which volume should be used?

**Comment by VoidXH** [comment]
Add 3 dB, and it will be fine.

**Comment by ValZapod** [comment]
>Some content (like Overwatch) has the top fronts and sides maxed out, and this is what fixes it.

Do DRP does not have that issue in Overwatch? Also are not such bad audio supposed to be just force clipped, not by doing loudness resizing, especially if you do it without standardized DRC?

**Comment by ValeZAA** [comment]
Fascinating! I found a test sample file that has Transitions and very complicated visual effects including when an object (and yes it does have dynamic objects that are actually flying) multiply so that one object becomes two objects and also it has  effect when one object occupies all the speakers to create Super Sound and reverb. Insane. Sounds good with Dolby Access (Atnos Headphones only + Realtek sound chip + GOOD Sony headphones)

https://disk.yandex.ru/i/NcvWSir_uTehfw
